#############################################################################
# Makefile for building: Bomberman
# Generated by qmake (3.0) (Qt 5.3.2)
# Project:  Bomberman.pro
# Template: app
# Command: /opt/qtsdk/5.3/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile Bomberman.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -pipe -g -Wall -W -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -fPIE $(DEFINES)
INCPATH       = -I/opt/qtsdk/5.3/gcc_64/mkspecs/linux-g++ -I.
LINK          = g++
LFLAGS        = -Wl,-rpath,/opt/qtsdk/5.3/gcc_64
LIBS          = $(SUBLIBS) -lsfml-graphics -lsfml-window -lsfml-system -lsfml-audio 
AR            = ar cqs
RANLIB        = 
QMAKE         = /opt/qtsdk/5.3/gcc_64/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		bomb.cpp \
		bomberman.cpp \
		brick.cpp \
		enemy.cpp \
		hiddenstaff.cpp \
		item.cpp 
OBJECTS       = main.o \
		bomb.o \
		bomberman.o \
		brick.o \
		enemy.o \
		hiddenstaff.o \
		item.o
DIST          = /opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/lex.prf \
		Bomberman.pro main.cpp \
		bomb.cpp \
		bomberman.cpp \
		brick.cpp \
		enemy.cpp \
		hiddenstaff.cpp \
		item.cpp
QMAKE_TARGET  = Bomberman
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = Bomberman


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Bomberman.pro /opt/qtsdk/5.3/gcc_64/mkspecs/linux-g++/qmake.conf /opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_pre.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/shell-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/linux.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-base.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-unix.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/qconfig.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_functions.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_config.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/linux-g++/qmake.conf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_post.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/exclusive_builds.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/resolve_config.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_post.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/warn_on.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/testcase_targets.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/exceptions.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/yacc.prf \
		/opt/qtsdk/5.3/gcc_64/mkspecs/features/lex.prf \
		Bomberman.pro
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Bomberman.pro
/opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_pre.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/shell-unix.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/unix.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/linux.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/gcc-base-unix.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-base.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/common/g++-unix.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/qconfig.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_functions.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/qt_config.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/linux-g++/qmake.conf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/spec_post.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/exclusive_builds.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_pre.prf:
deployment.pri:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/resolve_config.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/default_post.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/warn_on.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/testcase_targets.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/exceptions.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/yacc.prf:
/opt/qtsdk/5.3/gcc_64/mkspecs/features/lex.prf:
Bomberman.pro:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile Bomberman.pro

qmake_all: FORCE

dist: 
	@test -d .tmp/Bomberman1.0.0 || mkdir -p .tmp/Bomberman1.0.0
	$(COPY_FILE) --parents $(DIST) .tmp/Bomberman1.0.0/ && (cd `dirname .tmp/Bomberman1.0.0` && $(TAR) Bomberman1.0.0.tar Bomberman1.0.0 && $(COMPRESS) Bomberman1.0.0.tar) && $(MOVE) `dirname .tmp/Bomberman1.0.0`/Bomberman1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Bomberman1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

main.o: main.cpp SFML/Graphics.hpp \
		SFML/Window.hpp \
		SFML/System.hpp \
		SFML/Config.hpp \
		SFML/System/Clock.hpp \
		SFML/System/Export.hpp \
		SFML/System/Time.hpp \
		SFML/System/Err.hpp \
		SFML/System/InputStream.hpp \
		SFML/System/Lock.hpp \
		SFML/System/NonCopyable.hpp \
		SFML/System/Mutex.hpp \
		SFML/System/Sleep.hpp \
		SFML/System/String.hpp \
		SFML/System/Thread.hpp \
		SFML/System/Thread.inl \
		SFML/System/ThreadLocal.hpp \
		SFML/System/ThreadLocalPtr.hpp \
		SFML/System/ThreadLocalPtr.inl \
		SFML/System/Utf.hpp \
		SFML/System/Utf.inl \
		SFML/System/Vector2.hpp \
		SFML/System/Vector2.inl \
		SFML/System/Vector3.hpp \
		SFML/System/Vector3.inl \
		SFML/Window/Context.hpp \
		SFML/Window/Export.hpp \
		SFML/Window/GlResource.hpp \
		SFML/Window/ContextSettings.hpp \
		SFML/Window/Event.hpp \
		SFML/Window/Joystick.hpp \
		SFML/Window/Keyboard.hpp \
		SFML/Window/Mouse.hpp \
		SFML/Window/VideoMode.hpp \
		SFML/Window/Window.hpp \
		SFML/Window/WindowHandle.hpp \
		SFML/Window/WindowStyle.hpp \
		SFML/Graphics/BlendMode.hpp \
		SFML/Graphics/Color.hpp \
		SFML/Graphics/Export.hpp \
		SFML/Graphics/Font.hpp \
		SFML/Graphics/Glyph.hpp \
		SFML/Graphics/Rect.hpp \
		SFML/Graphics/Rect.inl \
		SFML/Graphics/Texture.hpp \
		SFML/Graphics/Image.hpp \
		SFML/Graphics/RenderStates.hpp \
		SFML/Graphics/Transform.hpp \
		SFML/Graphics/RenderTexture.hpp \
		SFML/Graphics/RenderTarget.hpp \
		SFML/Graphics/View.hpp \
		SFML/Graphics/PrimitiveType.hpp \
		SFML/Graphics/Vertex.hpp \
		SFML/Graphics/RenderWindow.hpp \
		SFML/Graphics/Shader.hpp \
		SFML/Graphics/Shape.hpp \
		SFML/Graphics/Drawable.hpp \
		SFML/Graphics/Transformable.hpp \
		SFML/Graphics/VertexArray.hpp \
		SFML/Graphics/CircleShape.hpp \
		SFML/Graphics/RectangleShape.hpp \
		SFML/Graphics/ConvexShape.hpp \
		SFML/Graphics/Sprite.hpp \
		SFML/Graphics/Text.hpp
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

bomb.o: bomb.cpp bomb.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomb.o bomb.cpp

bomberman.o: bomberman.cpp bomberman.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bomberman.o bomberman.cpp

brick.o: brick.cpp brick.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o brick.o brick.cpp

enemy.o: enemy.cpp enemy.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o enemy.o enemy.cpp

hiddenstaff.o: hiddenstaff.cpp hiddenstaff.h \
		item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o hiddenstaff.o hiddenstaff.cpp

item.o: item.cpp item.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o item.o item.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/Bomberman/bin || mkdir -p $(INSTALL_ROOT)/opt/Bomberman/bin
	-$(INSTALL_PROGRAM) "$(QMAKE_TARGET)" "$(INSTALL_ROOT)/opt/Bomberman/bin/$(QMAKE_TARGET)"

uninstall_target: FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/opt/Bomberman/bin/$(QMAKE_TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/Bomberman/bin/ 


install:  install_target  FORCE

uninstall: uninstall_target   FORCE

FORCE:

